version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: db
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  web:
    build:
      dockerfile: Dockerfile
    container_name: web
    depends_on:
      - db
    volumes:
      - static_volume:/project/static
      - media_volume:/project/media
    env_file:
      - ./.env
    command: >
      bash -c "./manage.py collectstatic --noinput && 
      ./manage.py makemigrations Authentication Object && 
      ./manage.py migrate  &&
      ./manage.py initadmin &&
      gunicorn -b 0.0.0.0:8000 project.wsgi:application"
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: docker/nginx
    container_name: nginx
    env_file:
      - ./.env
    volumes:
      - static_volume:/project/static
      - media_volume:/project/media
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"

volumes:
  static_volume:
  media_volume:
  postgres_storage:
