apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-django-app
  labels:
    app.kubernetes.io/name: django
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.replicasCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: django
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: django
        app.kubernetes.io/component: backend
    spec:
      containers:
        - image: {{ .Values.container.django }}
          name: {{ .Release.Name }}-django-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.config.django.port }}
              name: gunicorn
          env:
            - name: SECRET_KEY
              value: {{ .Values.config.django.SECRET_KEY }}
            - name: DEBUG
              value: {{ .Values.config.django.DEBUG }}
            - name: DATABASE_NAME
              value: {{ .Values.config.postgres.POSTGRES_DB }}
            - name: DATABASE_USER
              value: {{ .Values.config.postgres.POSTGRES_USER }}
            - name: DATABASE_PASSWORD
              value: {{ .Values.config.postgres.POSTGRES_PASSWORD }}
            - name: DATABASE_HOST
              value: {{ .Values.config.postgres.POSTGRES_HOST }}
            - name: DATABASE_PORT
              value: {{ .Values.config.postgres.POSTGRES_PORT }}
            - name: YANDEX_GEOCODER
              value: {{ .Values.config.django.YANDEX_GEOCODER }}
