apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-django-service
  labels:
    app: {{ .Release.Name }}-django-service
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-django-service
  ports:
    - port: 8000
      targetPort: 8000