apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app.kubernetes.io/name: database-service
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.postgres.POSTGRES_PORT }}
      targetPort: database
      protocol: TCP
      name: database
  selector:
    app.kubernetes.io/name: database-service
    app.kubernetes.io/component: service